#!/bin/zsh

#####################################################################
# This file contains several functions that represent tasks
#
# In order to run them easily, add the following alias to your shell:
# > echo "alias task='./taskfile'" >> ~/.zshrc
#
# After that, you can run the tasks as follows:
# > task <function_name>
#####################################################################


# Enable shell strict mode
# Reference: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

# This is an example task
hello_world() {
    echo "Hello world!"
}

run_Server(){
    python HTTPService.py
}
run_HTTPService() {
    endpoint="$1"
    query="$2"
    echo $endpoint
    if [$query= '']
    then
        curl localhost:8080/$endpoint
    else
    curl localhost:8080/$endpoint+'?name='+$query
    fi
}

# Tries to run the parameter as if it was a function
# Reference: https://stackoverflow.com/a/16159057/3203441
"$@" 